---
openapi: 3.0.3
info:
  title: Register of training providers API
  version: v0
servers: []
paths:
  "/api/{api_version}/info":
    get:
      summary: Provides general information about the API
      description: This endpoint can be used to retrieve general information about
        the API.
      tags:
      - Info
      parameters:
      - name: Authorization
        in: header
        required: true
        schema:
          type: string
        example: test_92db1241b8721bddb4540fdbb4b1a56d4bbb54a006bd6086b133ff0ced37eb12
        description: A valid API token must be provided in the Authorization header
          to access this endpoint.
      - name: api_version
        in: path
        required: true
        schema:
          type: string
        example: v0
        description: The API version to use in the request path. This should be set
          to the latest version for this endpoint.
      responses:
        '200':
          description: returns the requested and latest API version and status
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  version:
                    type: object
                    properties:
                      requested:
                        type: string
                      latest:
                        type: string
                    required:
                    - requested
                    - latest
                required:
                - status
                - version
              example:
                status: ok
                version:
                  requested: v0
                  latest: v0
        '401':
          description: returns 401 Unauthorized for invalid token
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                required:
                - error
              example:
                error: Unauthorized
  "/api/{api_version}/providers":
    get:
      summary: Get many providers
      description: |
        This endpoint can be used to retrieve providers for a given academic year.
        This is intended to make it possible to check for new or updated providers regularly.
      tags:
      - providers
      parameters:
      - name: Authorization
        in: header
        required: true
        schema:
          type: string
        example: test_a48205de0776aee35373e13f6bd5ca66c3c2428e27d2562bcc6ea6be3bcad960
        description: A valid API token must be provided in the Authorization header
          to access this endpoint.
      - name: academic_year
        in: query
        required: false
        schema:
          type: integer
        example: 2025
        description: |
          Filters providers by the specified academic year. The value
          must be a 4-digit year, for example 2025. If not provided, the API will
          return providers active in the current academic year.
      - name: api_version
        in: path
        required: true
        schema:
          type: string
        example: v0
        description: The API version to use in the request path. This should be set
          to the latest version for this endpoint.
      - name: changed_since
        in: query
        required: false
        schema:
          type: string
        example: '2025-09-14T11:34:56Z'
        description: |
          Filters providers to only those updated after the specified timestamp.
          The value must be an ISO 8601 datetime, for example: 2025-09-14T11:34:56Z.
      responses:
        '200':
          description: returns an array of training providers
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        operating_name:
                          type: string
                        provider_type:
                          type: string
                        code:
                          type: string
                        accreditation_status:
                          type: string
                        ukprn:
                          type: string
                        urn:
                          type: string
                          nullable: true
                        updated_at:
                          type: string
                      required:
                      - id
                      - operating_name
                      - provider_type
                      - code
                      - accreditation_status
                      - ukprn
                      - urn
                      - updated_at
                required:
                - data
              example:
                data:
                - id: 3172f5c2-8bd3-440c-807e-5d4c971e888c
                  operating_name: School-centred initial teacher training (SCITT)
                    1063
                  provider_type: scitt
                  code: 93W
                  accreditation_status: accredited
                  ukprn: '69843359'
                  urn: '625172'
                  updated_at: '2025-09-15T11:34:56Z'
                - id: 7bcf4928-a0c7-4fa7-aa46-d4297eec31e0
                  operating_name: School 7320
                  provider_type: school
                  code: 98W
                  accreditation_status: unaccredited
                  ukprn: '52849471'
                  urn: '31673'
                  updated_at: '2025-09-15T11:34:56Z'
                - id: 06f04c46-bf0f-4161-8f29-a986bf4e548f
                  operating_name: Higher education institution (HEI) 1668
                  provider_type: hei
                  code: 4LK
                  accreditation_status: accredited
                  ukprn: '98088407'
                  urn:
                  updated_at: '2025-09-15T11:34:56Z'
                - id: 2c0f6229-c3a5-4760-a960-de8d0fb16de6
                  operating_name: Higher education institution (HEI) 7480
                  provider_type: hei
                  code: ETU
                  accreditation_status: unaccredited
                  ukprn: '12544338'
                  urn:
                  updated_at: '2025-09-15T11:34:56Z'
                - id: bfe71f91-e0fe-40bd-affa-2839e412999a
                  operating_name: Other 4570
                  provider_type: other
                  code: '917'
                  accreditation_status: accredited
                  ukprn: '56255493'
                  urn:
                  updated_at: '2025-09-15T11:34:56Z'
                - id: 7ca5c9b9-3427-49c4-9ba7-888b37b6fe9c
                  operating_name: Other 6343
                  provider_type: other
                  code: WNO
                  accreditation_status: unaccredited
                  ukprn: '19092440'
                  urn:
                  updated_at: '2025-09-15T11:34:56Z'
        '401':
          description: returns 401 Unauthorized for invalid token
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                required:
                - error
              example:
                error: Unauthorized
