---
openapi: 3.0.3
info:
  title: Register of training providers API
  version: v1
servers: []
paths:
  "/api/{api_version}/*url":
    get:
      summary: Invalid API version
      tags:
      - Core
      parameters:
      - name: api_version
        in: path
        required: true
        schema:
          type: string
        example: v0
      - name: url
        in: path
        required: true
        schema:
          type: string
        example: providers
      responses:
        '404':
          description: returns 404 Not Found for invalid version
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        error:
                          type: string
                        message:
                          type: string
                      required:
                      - error
                      - message
                required:
                - errors
              example:
                errors:
                - error: NotFound
                  message: Not found
  "/api/{api_version}/info":
    get:
      summary: Provides general information about the API
      tags:
      - Info
      parameters:
      - name: api_version
        in: path
        required: true
        schema:
          type: string
        example: v1
      responses:
        '200':
          description: returns the requested and latest API version and status
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  version:
                    type: object
                    properties:
                      requested:
                        type: string
                      latest:
                        type: string
                    required:
                    - requested
                    - latest
                required:
                - status
                - version
              example:
                status: ok
                version:
                  requested: v1
                  latest: v1
        '401':
          description: returns 401 Unauthorized for invalid token
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                required:
                - error
              example:
                error: Unauthorized
  "/api/{api_version}/providers":
    get:
      summary: Get many providers
      tags:
      - providers
      parameters:
      - name: api_version
        in: path
        required: true
        schema:
          type: string
        example: v1
      responses:
        '200':
          description: |
            This endpoint can be used to retrieve providers for a given academic year.
            This is intended to make it possible to check for new or updated providers regularly.
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        operating_name:
                          type: string
                        provider_type:
                          type: string
                        code:
                          type: string
                        accreditation_status:
                          type: string
                        updated_at:
                          type: string
                      required:
                      - id
                      - operating_name
                      - provider_type
                      - code
                      - accreditation_status
                      - updated_at
                required:
                - data
              example:
                data:
                - id: db05f4ef-9a42-4729-9a8f-19aa671b36b2
                  operating_name: Clearcourt College
                  provider_type: hei
                  code: DM3
                  accreditation_status: unaccredited
                  updated_at: '2025-09-15T12:34:56Z'
        '401':
          description: returns 401 Unauthorized for invalid token
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                required:
                - error
              example:
                error: Unauthorized
