---
EnableDefaultLinters: true
exclude:
  - "vendor/**/*"
  - "node_modules/**/*"
  - "tmp/**/*"
linters:
  ErbSafety:
    enabled: true
  StrictLocals:
    enabled: true
  Rubocop:
    enabled: false
    rubocop_config:
      inherit_from:
        - .rubocop.yml
