require:
  - ./lib/rubocop/cop/environment/no_direct_env_access.rb

inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rails.yml

inherit_from:
  - node_modules/@prettier/plugin-ruby/rubocop.yml

inherit_mode:
  merge:
    - Exclude

Style/NumericLiterals:
  Exclude:
    - db/schema.rb

Rails/CreateTableWithTimestamps:
  Exclude:
    - db/migrate/20250512104418_install_audited.rb

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: never
  SafeAutoCorrect: true

Environment/NoDirectEnvAccess:
  Enabled: true
  Exclude:
    - config/**/*
    - spec/**/*
    - lib/env.rb

Layout/IndentationWidth:
  Enabled: true
  Width: 2

Layout/FirstHashElementIndentation:
  Enabled: true

Layout/ArgumentAlignment:
  Enabled: true
  EnforcedStyle: with_fixed_indentation

Layout/MultilineMethodCallIndentation:
  Enabled: true

Layout/LineLength:
  Enabled: true
  Exclude:
    - "app/views/**/*.erb"
