flowchart TD
  effective_date["Effective Date"]
  new_operating_name["New Operating Name"]
  check_your_answers["Check Your Answers"]
  effective_date --> new_operating_name
  new_operating_name --> check_your_answers
