flowchart TD
  effective_date["Effective Date"]
  new_legal_name["New Legal Name"]
  check_your_answers["Check Your Answers"]
  effective_date --> new_legal_name
  new_legal_name --> check_your_answers
