flowchart TD
  effective_academic_year["Effective Academic Year"]
  provider_code["Provider Code"]
  check_your_answers["Check Your Answers"]
  effective_academic_year --> provider_code
  provider_code --> check_your_answers
