name: Set API access
concurrency: api_access_${{ github.ref_name }}

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Enable or disable API access"
        required: true
        type: choice
        default: staging
        options:
          - review
          - qa
          - staging
          - production
      enable_api_access:
        required: true
        type: choice
        options:
          - true
          - false
      docker-image-tag:
        description: "Docker image tag to deploy"
        required: true
        type: string
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [opened, reopened, synchronize, labeled]
  merge_group:
    branches:
      - main

env:
  TERRAFORM_BASE: terraform/application
  HEALTHCHECK_CMD: "healthcheck"
  FEATURE_API_FLAG: ${{ inputs.enable_api_access }}

jobs:
  api_access:
    name: Set api access
    environment:
      name: ${{ inputs.environment }}
      url: ${{ steps.deploy_manual.outputs.environment_url }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      pull-requests: write

    steps:
      - name: Deploy app to ${{ inputs.environment }}
        id: deploy_manual
        uses: DFE-Digital/github-actions/deploy-to-aks@master
        with:
          azure-client-id: ${{ secrets.AZURE_CLIENT_ID }}
          azure-subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          azure-tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          environment: ${{ inputs.environment }}
          pr-number: ${{ inputs.pull-request-number }}
          sha: ${{ inputs.docker-image-tag }}
          terraform-base: ${{ env.TERRAFORM_BASE }}
          healthcheck: ${{ env.HEALTHCHECK_CMD }}
          teams-webhook-url: ${{ secrets.TEAMS_WEBHOOK_URL }}
          service: ${{ vars.TEAMS_MSG_SERVICE_NAME }}
          db-seed: ${{ contains(fromJson('["review", "qa"]'), inputs.environment) && 'true' || 'false' }}
          gcp-wip: ${{ vars.GCP_WIP }}
          gcp-project-id: ${{ vars.GCP_PROJECT_ID }}
