name: Set API access
concurrency: api_access_${{ github.ref_name }}

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Enable or disable API access"
        required: true
        type: choice
        default: review
        options:
          - review
          - qa
          - staging
          - production
      enable_api_access:
        required: true
        type: choice
        options:
          - true
          - false
      docker-image-tag:
        description: "Docker image tag to deploy"
        required: true
        type: string
      pull-request-number:
        description: "Pull request number (required for review environment)"
        required: false
        type: string

env:
  TERRAFORM_BASE: terraform/application
  HEALTHCHECK_CMD: "healthcheck"
  TOOL_VERSIONS_FILE: .tool-versions

jobs:
  set_api_access:
    name: Set API access
    environment:
      name: ${{ inputs.environment }}
      url: ${{ steps.set_api_access.outputs.environment_url }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      pull-requests: write

    steps:
      - uses: azure/login@v3
        with:
          azure-client-id: ${{ secrets.AZURE_CLIENT_ID }}
          azure-subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          azure-tenant-id: ${{ secrets.AZURE_TENANT_ID }}

      - name: Install kubectl
        uses: DFE-Digital/github-actions/set-kubectl@master

      - uses: DFE-Digital/github-actions/set-kubelogin-environment@master
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}

      - name: Set environment variables
        run: |
          source global_config/${{ inputs.environment }}.sh
          tf_vars_file=${{ env.TF_VARS_PATH }}/${{ inputs.environment }}.tfvars.json
          echo "NAMESPACE=$(jq -r '.namespace' ${tf_vars_file})" >> $GITHUB_ENV

      - name: Set up cluster environment variables
        shell: bash
        run: |
          case ${{ env.CLUSTER }} in
            test)
              echo "cluster_rg=s189t01-tsc-ts-rg" >> $GITHUB_ENV
              echo "cluster_name=s189t01-tsc-test-aks" >> $GITHUB_ENV
              ;;
            platform-test)
              echo "cluster_rg=s189t01-tsc-pt-rg" >> $GITHUB_ENV
              echo "cluster_name=s189t01-tsc-platform-test-aks" >> $GITHUB_ENV
              ;;
            production)
              echo "cluster_rg=s189p01-tsc-pd-rg" >> $GITHUB_ENV
              echo "cluster_name=s189p01-tsc-production-aks" >> $GITHUB_ENV
              ;;
            *)
              echo "unknown cluster"
              ;;
          esac

      - name: K8 setup
        shell: bash
        run: |
          az aks get-credentials --overwrite-existing -g ${{ env.cluster_rg }} -n ${{ env.cluster_name }}
          kubelogin convert-kubeconfig -l $AAD_LOGIN_METHOD
      - name: Set API feature flag
        shell: bash
        run: |
          if [ "${{ inputs.environment }}" == "review"]
            kubectl -n bat-${{ env.NAMESPACE }} set env deployment/register-training-providers-${{ inputs.pull-request-number }} FEATURE_FLAG_API=${{ inputs.enable_api_access }}
          else
            kubectl -n bat-${{ env.NAMESPACE }} set env deployment/register-training-providers-${{ inputs.environment }} FEATURE_FLAG_API=${{ inputs.enable_api_access }}
          fi
      - name: Monitor restart
        shell: bash
        run: |
          while kubectl -n bat-${{ env.NAMESPACE }} get pods | grep register-training-providers-production | grep -q Terminating
          do
            echo "Restarting"
            sleep 5s
          done

          if ${{ inputs.enable_api_access }}
            "API access enabled"
          else
            "API access disabled"
          fi
